### ISSUE TITLE
Configuration reloading

### ISSUE THREAD

**Issue by nike38rus** [tomcat-slf4j-logback/tomcat-slf4j-logback#174]
Is it possible to turn on the automatic configuration reloading? I tried to specify the 'scan="true"' attribute in logback.xml, but that's not worked for me

**Comment by hazendaz** [comment]
I'm not sure if that is possible or not.  What I would suggest was trying to see if regular tomcat juli logging supports the same since this is doing nothing more than mimicing that.  If the standard one does it, then I think it is something we should look at supporting.  Personally I never change the log settings so I haven't run into this situation.

**Comment by nike38rus** [comment]
@hazendaz JULI is definitely doesn't support this but logback-classic does so I hope there is some way to make it reload configuration using the logback-classic out of the box capabilities. Can you make some research please? This feature will be very useful for my and others needs

**Comment by hazendaz** [comment]
@nike38rus I'm accepting this for research.  I don't know when I will have time to look into this but certainly welcome any time you can provide.  Thanks for confirming juli doesn't support this feature so if we can pull this off I think that makes this an even more viable library replacement.

**Comment by hazendaz** [comment]
closing this old ticket.  nothing was ever done here and not sure if feasible.  At any rate, the repos here are long split into separate modules, I can to archive this one in future here after cleaning up the documentation throughout.
