### ISSUE TITLE
missing maven central dependencies

### ISSUE THREAD

**Issue by schulzp** [tomcat-slf4j-logback/tomcat-slf4j-logback#178]
Hi,

I tried to use `tomcat85-slf4j-logback:8.5.15` but it cannot be found on maven central (only `8.5.14`). If I downgrade to `8.5.14`, the parent `tomcat-slf4j-logback:1.0.5` cannot be found (only `1.0.4`). Could you please fix that? Is there an alternative repository to be used?

**Comment by hazendaz** [comment]
@schulzp Thanks for reporting this.  I'm not sure what occurred on parent 1.0.5.  I have pushed a release to central.  Please check in a few hours to verify that it is there now.

As for tomcat releases...because I use one shot to release these, I have not released any update to tomcat 8.5.15 or 9.0.0.M21 yet.  While there are vulnerabilities against tomcat they are not against the pieces of juli and more importantly against what we provide.  So updates are far less important in this area of the code.  In the meantime though, if you check under github releases on this project you will find the bundles you are looking for.

**Comment by hazendaz** [comment]
@schulzp I confirmed parent 1.0.5 is now in central.  I'm going to close this for now since this satisfies the question you raised.  If you would still like other tomcats released to central rather than using github releases at this time, please open another ticket and I'll look at getting that going but that might take a week or so due to availability.  Thanks.

**Comment by schulzp** [comment]
Awesome @hazendaz, thanks for the quick reply!

**Comment by hazendaz** [comment]
@schulzp I have went ahead and released tomcat 8.5.15 and 9.0.0.M21.  This should be sync'd to maven central in next couple of hours.  I mainly did this now as next tomcat versions are already out and per your need as well.  Let me know if this works out for you.  Thanks.

**Comment by hazendaz** [comment]
@schulzp tomcat 8.5.16 and 9.0.0.M22 have been released to github releases.

**Comment by schulzp** [comment]
Cool, thanks @hazendaz. I'm disappointed since the classic syslog appender cannot be used with the access valve. 😠
