### ISSUE TITLE
Missed files

### ISSUE THREAD

**Issue by fedexin40** [tomcat-slf4j-logback/tomcat-slf4j-logback#193]
Hello guys @hazendaz

First of all thanks for your job, as always amazing :+1: 

And now passing to the issue I have some doubts about the [the Quick Start documentation](https://github.com/tomcat-slf4j-logback/tomcat-slf4j-logback#quick-start)

1.- bin/tomcat-juli.jar to $CATALINA_HOME/bin (replacing existing tomcat-juli.jar)
I downloaded the tomcat-slf4j-logback but there is not any tomcat-juli.jar inside. Maybe do you refer to the file which is available as an "extra" component for tomcat. [According to this page in Using Log4j section](https://tomcat.apache.org/tomcat-8.0-doc/logging.html)?

2.-  bin/setenv.sh or bin\setenv.bat to $CATALINA_HOME/bin
Well after looking for this file, it is not exactly in bin in fact it is `src/assembly/bin/` I know I am exaggerating.

3.-  I cannot see the file logback-core-1.2.1.jar and either the file logback-access-1.2.1.jar, where could I find them?

Thanks in advance guys for your help

**Comment by hazendaz** [comment]
@fedexin40 

1 - What do you mean when you say you downloaded it and it's missing tomcat-juli under bin?  The releases section has nearly every version of 6, 7, 8, 8.5, and 9.  Those zip packages all include bin/tomcat-juli as well as every other configuratino file.  In fact, you can simply unzip as instructed in tomcat root catalina home and it will patch the files.

2 - You have downloaded the source, not the distros.  If you are downloading the source, you need to run 'mvn clean install' to build the package.  Otherwise see releases section or even check maven central as all distros are there now too.

3 - Please download from releases.  The source code does not house jars.  It's a maven project.  If you pull the source code directly you will need to run a maven build which will pull all items and place into target folders for various tomcat versions still supported (ie 7 through 9).

**Comment by fedexin40** [comment]
Thanks for your help, as you have noticed I am newbie but thanks to you  I learnt new things today

**Comment by hazendaz** [comment]
Your welcome

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
